#!/usr/bin/env node
'use strict';

var XMPP = require('stanza.io');
var should = require('should');
var async = require('async');
var log = require('../libs/log');

var debug = false;

var users = {
    'Han_Solo': {
        jid:      'chewie.solo@localhost',
        password: 'pass123',
        host:     'localhost',
        debugOptions: {
            keysColor: 'cyan'
        }
    },
    'Chewie': {
        jid:      'chewbacca@localhost',
        password: 'pass123',
        host:     'localhost',
        debugOptions: {
            keysColor: 'yellow'
        }
    }
};

describe('stanza.io offline message receive test', function () {

    var chewie;

    it('A client should connect and receive offline message(s)', function (done) {
        this.timeout(10000);

        async.series([

            function (cb) {
                chewie = XMPP.createClient({
                    jid: users.Chewie.jid,
                    password: users.Chewie.password,
                    wsURL: 'ws://localhost:5280/websocket',
                    transport: 'websocket'
                });

                cb();
            },

            function (cb) {
                if (debug === true) {
                    chewie.on('*', function (name, data) {
                        log(users.Chewie.debugOptions, name, data);
                    });
                }
                cb();
            },

            function (cb) {
                chewie.on('message', function (msg) {
                    should(msg).have.property('to');
                    msg.to.full.should.equal(users.Chewie.jid);
                    should(msg).have.property('body', 'Chewie, are you there?');
                    log(users.Han_Solo.debugOptions, msg);
                });
                cb();
            },

            function (cb) {
                chewie.once('session:started', function () {
                    cb();
                });

                chewie.connect();
            },

            function (cb) {
                chewie.getRoster(function (err, resp) {
                    if (err) {
                        console.log(err);
                    } else {
                        should(resp).have.property('roster');
                        should(resp).have.property('from')
                        resp.from.full.should.equal(users.Chewie.jid);
                        log(users.Chewie.debugOptions, resp);
                    }
                    cb();
                });
            },

            function (cb) {
                chewie.sendPresence({
                    
                });
                cb();
            },

            function () {
                done();
            }

        ]);
    });

    after(function() {
        chewie.disconnect();
    });
});